services:
  - docker

branches:
  only:
    - /^v\d+\.\d+\.\d+.*$/  # version tags

notifications:
  email:
    recipients:
      - edoardo.romiti@iit.it
      - arturo.laurenzi@iit.it
    on_success: never
    on_failure: always
    

before_install:
  - set -e
  - echo "Travis tag is $TRAVIS_TAG"
  - ./docker/build-docker.bash
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - set +e

script: 
  - docker push arturolaurenzi/concert_description:latest
  - docker tag arturolaurenzi/concert_description:latest arturolaurenzi/concert_description:$TRAVIS_TAG
  - docker push arturolaurenzi/concert_description:$TRAVIS_TAG