solver_options:
  regularization: 1e-12
  back_end: qpoases
  front_end: ihqp

stack:
  - [LF, RF, LR, RR]

constraints: [Postural]

params:
  - &wheel_radius 0.16

Postural:
  type: Postural
  lambda: 0.
  disabled_joints:
    - VIRTUALJOINT_1
    - VIRTUALJOINT_2
    - VIRTUALJOINT_3
    - VIRTUALJOINT_4
    - VIRTUALJOINT_5
    - VIRTUALJOINT_6

# we've got no IMU (actually we do, from T cameras)
# IMU:
#     type: Cartesian
#     distal_link: imu_link
#     lambda: 0.1
#     indices: [3,4,5]
#     weight: 1.
#     active: false

LF:
  type: WheelRolling
  wheel_name: wheel_A
  lib_name: libcentauro_cartesio_addon.so
  wheel_radius: *wheel_radius
  include_z_axis: true

RF:
  type: WheelRolling
  wheel_name: wheel_B
  lib_name: libcentauro_cartesio_addon.so
  wheel_radius: *wheel_radius
  include_z_axis: true

LR:
  type: WheelRolling
  wheel_name: wheel_C
  lib_name: libcentauro_cartesio_addon.so
  wheel_radius: *wheel_radius
  include_z_axis: true

RR:
  type: WheelRolling
  wheel_name: wheel_D
  lib_name: libcentauro_cartesio_addon.so
  wheel_radius: *wheel_radius
  include_z_axis: true
